services:
  lexfcs-endpoint:
    build: .
    container_name: pdl-lexfcs
    environment:
      MONGODB_URI: "mongodb://admin:${MONGO_PASSWORD}@pdl-mongodb:27017/admin"
      MONGODB_DB: "lex"
      BASE_URL: "${BASE_URL:-https://lexfcs.lexoterm.de}"
    networks:
      - pdl-network
    restart: unless-stopped

networks:
  pdl-network:
    external: true
    name: ${DOCKER_NETWORK:-pdl-deployment_pdl-network}